import { Inter } from "next/font/google";
import "./globals.css";
import CombinedProvider from './components/CombinedProvider'; // Adjust the path as needed

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <CombinedProvider>
          {children}
        </CombinedProvider>
      </body>
    </html>
  );
}
